### ISSUE TITLE
"Deprecated" message

### ISSUE THREAD

**Issue by paulrudy** [torsten-sauer/social-media-links#2]
I'm getting the following message:

> : Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` 
> in xxxx/grav/user/plugins/social-media-links/social-media-links.php
> on line
> 69

**Comment by torsten-sauer** [comment]
Thanks for your report.

This looks like a warning that shouldn't impact functionality. I think I can provide a fix in a few days but if you'd like you can contribute a small fix yourself and I will merge it.

**Comment by paulrudy** [comment]
I'm sorry, I don't know PHP, so I can't usefully contribute. Just reporting :)

**Comment by paulrudy** [comment]
PR #3 fixes this

**Comment by torsten-sauer** [comment]
Thx @paulrudy for your PR, I'm really ashamed, that I forgot this totally...

**Comment by paulrudy** [comment]
No worries at all!
