### ISSUE TITLE
Exception thrown when running as localhost

### ISSUE THREAD

**Issue by bjazmoore** [torsten-sauer/social-media-links#4]
I get the error message: 

> 0 - An exception has been thrown during the rendering of a template ("Object of class Grav\Common\Page\Media could not be converted to number"). 

when I am running the plugin - checking for enabled when running as localhost:8000 or a localhost under WAMP.  I do not get this error when running on Linux on my host.  I have isolated it to some code that checks to see if the plugin is enabled:

```
{% if config.plugins.social-media-links.enabled %}
  {% include 'partials/socialmedia.html.twig' %}
{% endif %}
```

Specifically: "config.plugins.social-media-links.enabled".   I did not see this in the doc's, but it makes sense this should work, and it does work running on my webhost.  I am not sure why it fails when running locally.

This is my configuration:

- PHP 7.4.33
- Chrome Browser
- Grav 1.7.42.3
- Theme: [Quark with Blog site skeleton](https://github.com/getgrav/grav-skeleton-blog-site)

Thanks

**Comment by torsten-sauer** [comment]
I couldn't reproduce your error - neither locally nor on my server(s). I also tried Linux and Windows - everything works here on my side :-(

As I'm not using grav (and my plugin) anymore it's a bit complicated to track down such errors for me. If you find where this error is coming from and have a solution (or some idea at least) feel free to answer here or open up an PR ;-)


Sidenote: This config switch is (or at least was when I did create this little addon) some kind of standard from a grav template, so I didn't add it to the docs. I think it is mainly shown here for enabling / disabling the plugin:
![image](https://github.com/torsten-sauer/social-media-links/assets/7765372/7301e6a9-4c0a-43e3-9eaf-958700a1ed6b)

**Comment by bjazmoore** [comment]
I am closing this issue as the problem observed is not technically an issue with this plugin, rather a behavior of the twig processor.  Quoting Bluitzen: 

> According to the documentation about [Config Variable Namespacing 1](https://learn.getgrav.org/17/basics/grav-configuration#config-variable-namespacing) the plugin filename is part of the config variable namespace and the filename of the [social-media-links](https://github.com/torsten-sauer/social-media-links) plugin includes dashes.
>
>So technically this namespace config.plugins.social-media-links.enabled is correct but as [@pamtbaau](https://discourse.getgrav.org/u/pamtbaau) pointed out will fail because Twig treats each dash as an operator (minus).

There are two work arounds suggested by this very kind user as well.  See them [here](https://discourse.getgrav.org/t/problem-with-inherited-theme/23672/6?u=bjaz) and [here](https://discourse.getgrav.org/t/problem-with-inherited-theme/23672/10?u=bjaz).

I am closing this issue.
